### ISSUE TITLE
Retreive mssql iso download url

### ISSUE THREAD

**Issue by FLuzzi-csw** [majkinetor/Install-SqlServer#3]
Hi @majkinetor , sorry to bother you.

I was curios how were you able to find the [SQL Server 2022 Development Edition Direct Download](https://github.com/majkinetor/Install-SqlServer#notes), i've search everywhere and even used wireshark, but I wasn't able to find it...

![da wae](https://images-wixmp-ed30a86b8c4ca887773594c2.wixmp.com/i/269434e4-c27f-44ca-9854-29b060b20cee/dbzx2mt-43444180-3016-4ac4-8ce4-a35cf021f572.png)

**Comment by majkinetor** [comment]
Hahahah, 

I was searching a lot around, then I was like, WTF MS, lets go for the wireshark and then I remembered that there is chocolatey package which I didn't use because I needed more loging and robustness:

https://community.chocolatey.org/packages/sql-server-2022#files
![image](https://user-images.githubusercontent.com/85767/236452207-4a39b198-4b0e-42d2-be03-6146a43c1259.png)

**Comment by FLuzzi-csw** [comment]
Choco FTW, thank you!

**Comment by majkinetor** [comment]
Now, I don't know how they found it so the question is not exactly resolved. 

Next thing was to see what MS SQL Server docker images do: https://hub.docker.com/_/microsoft-mssql-server.
Quick search revealed nothing.

But here is something interesting, now that we have URL which I search for using DDG:

https://blog.dotsmart.net/2022/11/24/sql-server-2022-localdb-download

So I guess now we know :)

**Comment by majkinetor** [comment]
Sure enough it works. Here is what I did:

1. Download evaluation from official site: https://www.microsoft.com/en-us/evalcenter/download-sql-server-2022
2. Unpack using 7zip
3. Search iso using grep

![image](https://user-images.githubusercontent.com/85767/236455566-67994eea-790a-43ed-9dde-2f2c075b2024.png)

**Comment by majkinetor** [comment]
I will add this to the README.md :) Thanks for the inspiration.

**Comment by FLuzzi-csw** [comment]
Well that blog post will be my new goto when searching for URL in installers!

Btw i've also found a more (I hope) [stable solution](https://github.com/bucrogers/Dockerfiles-for-windows/tree/master/sqlexpress) using directly the provided installer.
As i try it i'll let you know 👍

**Comment by FLuzzi-csw** [comment]
> Well that blog post will be my new goto when searching for URL in installers!
> 
> Btw i've also found a more (I hope) stable but less customized [solution](https://github.com/bucrogers/Dockerfiles-for-windows/tree/master/sqlexpress) using directly the provided installer. As i try it i'll let you know 👍

At the end that solution is not working (at least for my problem), but i found the [official mssql docker image](https://github.com/microsoft/mssql-docker/tree/master/windows/mssql-server-windows-developer) that actually worked first try 🤤

**Comment by majkinetor** [comment]
It doesnt have anything to do with your original question. 

Windows containers work only on Windows Server anyway. Developers do not use servers.

**Comment by FLuzzi-csw** [comment]
You right i got carried by this little journey 😄
Thanks, this will be super usefull!

**Comment by majkinetor** [comment]
Yeah, I noticed :P

Anyway, I added it [here](https://github.com/majkinetor/Install-SqlServer#how-to-find-sql-server-direct-download)

Cheers.
